name: fast-crypto-exchange
base: core22
version: '1.0.0'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

icon: snap/gui/logo.png  
title: Fast Crypto Exchange

grade: stable # devel / stable
confinement: strict # devmode / strict

architectures:
  - build-on: amd64

apps:
  fast-crypto-exchange:
    command: snap/command-chain/desktop-launch $SNAP/bin/fast-crypto-exchange
    plugs:
      - network
      - network-status
    extensions:
      - gnome

parts:
  fast-crypto-exchange:
    plugin: python
    source: .